import { defineStore } from 'pinia'
import { useToast } from 'vue-toastification'
import { sortBy } from 'lodash'

const toast = useToast()

export const useUtilStore = defineStore({
  id: 'utilStore',
  state: () => ({
    genres: ['Dark Electro', 'EBM', 'Aggrotech', 'Industrial', 'Black Industrial', 'Black Metal', 'Raw Black Metal', 'Melodic Death'].sort(),
    countries: [
      { value: '', title: 'Любая' },
      { value: 'Afghanistan', title: 'Афганистан' },
      { value: 'Åland Islands', title: 'Аландские острова' },
      { value: 'Albania', title: 'Албания' },
      { value: 'Algeria', title: 'Алжир' },
      { value: 'American Samoa', title: 'Американские Самоа' },
      { value: 'Andora', title: 'Андора' },
      { value: 'Angola', title: 'Ангола' },
      { value: 'Anguilla', title: 'Ангилья' },
      { value: 'Antarctica', title: 'Антарктика' },
      { value: 'Antigua and Barbuda', title: 'Антигуа и Барбуда' },
      { value: 'Argentina', title: 'Аргентина' },
      { value: 'Armenia', title: 'Армения' },
      { value: 'Aruba', title: 'Аруба' },
      { value: 'Australia', title: 'Австралия' },
      { value: 'Austria', title: 'Австрия' },
      { value: 'Azerbaijan', title: 'Азербайджан' },
      { value: 'Bahamas', title: 'Багамы' },
      { value: 'Bahrain', title: 'Бахрейн' },
      { value: 'Bangladesh', title: 'Бангладеш' },
      { value: 'Barbados', title: 'Барбадос' },
      { value: 'Belarus', title: 'Беларусь' },
      { value: 'Belgium', title: 'Бельгия' },
      { value: 'Belize', title: 'Белиз' },
      { value: 'Benin', title: 'Бенин' },
      { value: 'Bermuda', title: 'Бермуды' },
      { value: 'Bhutan', title: 'Бутан' },
      { value: 'Bolivia', title: 'Боливия' },
      { value: 'Bosnia and Herzegovina', title: 'Босния и Герцеговина' },
      { value: 'Botswana', title: 'Ботсвана' },
      { value: 'Bouvet Island', title: 'Остров Буве' },
      { value: 'Brazil', title: 'Бразилия' },
      { value: 'British Indian Ocean Territory', title: 'Британская Территория в Индийском Океане' },
      { value: 'Brunei Darussalam', title: 'Бруней' },
      { value: 'Bulgaria', title: 'Болгария' },
      { value: 'Burkina Faso', title: 'Буркина Фасо' },
      { value: 'Burundi', title: 'Бурунди' },
      { value: 'Cambodia', title: 'Камбоджия' },
      { value: 'Cameroon', title: 'Камерун' },
      { value: 'Canada', title: 'Канада' },
      { value: 'Cape Verde', title: 'Капе Верде' },
      { value: 'Cayman Islands', title: 'Каймановы острова' },
      { value: 'Central African Republic', title: 'Центральная Африканская Республика' },
      { value: 'Chad', title: 'Чад' },
      { value: 'Chile', title: 'Чили' },
      { value: 'China', title: 'Китай' },
      { value: 'Christmas Island', title: 'Остров Рождества (Австралия)' },
      { value: 'Cocos (Keeling) Islands', title: 'Кокосовые островаC' },
      { value: 'Colombia', title: 'Колумбия' },
      { value: 'Comoros', title: 'Коморы' },
      { value: 'Congo', title: 'Конго' },
      { value: 'Congo, The Democratic Republic of the', title: 'Демократическая Республика Конго' },
      { value: 'Cook Islands', title: 'Острова Кука' },
      { value: 'Costa Rica', title: 'Коста Рика' },
      { value: 'Croatia', title: 'Хорватия' },
      { value: 'Cuba', title: 'Куба' },
      { value: 'Cyprus', title: 'Кипр' },
      { value: 'Czech Republic', title: 'Чешская Республика' },
      { value: 'Czechia', title: 'Чешская Республика' },
      { value: 'Denmark', title: 'Дания' },
      { value: 'Djibouti', title: 'Джибути' },
      { value: 'Dominica', title: 'Доминика' },
      { value: 'Dominican Republic', title: 'Доминиканская Республика' },
      { value: 'Ecuador', title: 'Эквадор' },
      { value: 'Egypt', title: 'Египет' },
      { value: 'El Salvador', title: 'Сальвадор' },
      { value: 'Equatorial Guinea', title: 'Экваториальная Гвинея' },
      { value: 'Eritrea', title: 'Эритрея' },
      { value: 'Estonia', title: 'Эстония' },
      { value: 'Ethiopia', title: 'Эфиопия' },
      { value: 'Falkland Islands (Malvinas)', title: 'Фолклендские острова' },
      { value: 'Faroe Islands', title: 'Фарерские острова' },
      { value: 'Fiji', title: 'Фиджи' },
      { value: 'Finland', title: 'Финляндия' },
      { value: 'France', title: 'Франция' },
      { value: 'French Guiana', title: 'Гвиана (департамент Франции)' },
      { value: 'French Polynesia', title: 'Французская Полинезия' },
      { value: 'French Southern Territories', title: 'Французские Южные и Антарктические территории' },
      { value: 'Gabon', title: 'Габон' },
      { value: 'Gambia', title: 'Гамбия' },
      { value: 'Georgia', title: 'Грузия' },
      { value: 'Germany', title: 'Германия' },
      { value: 'Ghana', title: 'Гана' },
      { value: 'Greece', title: 'Греция' },
      { value: 'Greenland', title: 'Гринландия' },
      { value: 'Grenada', title: 'Гренада' },
      { value: 'Guadeloupe', title: 'Гваделупа' },
      { value: 'Guam', title: 'Гуам' },
      { value: 'Guatemala', title: 'Гватемала' },
      { value: 'Guernsey', title: 'Гернси' },
      { value: 'Guinea', title: 'Гвинея' },
      { value: 'Guinea-Bissau', title: 'Гвинея-Бисау' },
      { value: 'Guyana', title: 'Гайна' },
      { value: 'Haiti', title: 'Гаити' },
      { value: 'Heard Island and Mcdonald Islands', title: 'Остров Херд и острова Макдональд' },
      { value: 'Holy See (Vatican City State)', title: 'Ватикан' },
      { value: 'Honduras', title: 'Гондурас' },
      { value: 'Hong Kong', title: 'Гонк Конг' },
      { value: 'Hungary', title: 'Венгрия' },
      { value: 'Iceland', title: 'Исландия' },
      { value: 'India', title: 'Индия' },
      { value: 'Indonesia', title: 'Нндонезия' },
      { value: 'Iran, Islamic Republic Of', title: 'Иран' },
      { value: 'Iraq', title: 'Ирак' },
      { value: 'Ireland', title: 'Ирландия' },
      { value: 'Isle of Man', title: 'Остров Мэн' },
      { value: 'Israel', title: 'Израиль' },
      { value: 'Italy', title: 'Италия' },
      { value: 'Jamaica', title: 'Ямайка' },
      { value: 'Japan', title: 'Япония' },
      { value: 'Jersey', title: 'Джерси' },
      { value: 'Jordan', title: 'Иордания' },
      { value: 'Kazakhstan', title: 'Казахстан' },
      { value: 'Kenya', title: 'Кения' },
      { value: 'Kiribati', title: 'Кирибати' },
      { value: 'Korea, Republic of', title: 'Южная Корея' },
      { value: 'Kuwait', title: 'Кувейт' },
      { value: 'Kyrgyzstan', title: 'Кыргызстан' },
      { value: 'Latvia', title: 'Латвия' },
      { value: 'Lebanon', title: 'Ливан' },
      { value: 'Lesotho', title: 'Лесото' },
      { value: 'Liberia', title: 'Либерия' },
      { value: 'Liechtenstein', title: 'Лихтенштейн' },
      { value: 'Lithuania', title: 'Литва' },
      { value: 'Luxembourg', title: 'Люксембург' },
      { value: 'Macao', title: 'Мокао' },
      { value: 'Macedonia, The Former Yugoslav Republic of', title: 'Македония' },
      { value: 'Madagascar', title: 'Мадагаскар' },
      { value: 'Malawi', title: 'Малавия' },
      { value: 'Malaysia', title: 'Малазия' },
      { value: 'Maldives', title: 'Мальдивы' },
      { value: 'Mali', title: 'Мали' },
      { value: 'Malta', title: 'Мальта' },
      { value: 'Marshall Islands', title: 'Маршалловы Острова' },
      { value: 'Martinique', title: 'Мартиника' },
      { value: 'Mauritania', title: 'Мавритания' },
      { value: 'Mauritius', title: 'Маврикий' },
      { value: 'Mayotte', title: 'Майотта' },
      { value: 'Mexico', title: 'Мексика' },
      { value: 'Micronesia, Federated States of', title: 'Микронезия' },
      { value: 'Moldova, Republic of', title: 'Молдова' },
      { value: 'Monaco', title: 'Монако' },
      { value: 'Mongolia', title: 'Монголия' },
      { value: 'Montserrat', title: 'Монтсеррат' },
      { value: 'Morocco', title: 'Мороко' },
      { value: 'Mozambique', title: 'Мозамбик' },
      { value: 'Myanmar', title: 'Мьянма' },
      { value: 'Namibia', title: 'Намибия' },
      { value: 'Nauru', title: 'Науру' },
      { value: 'Nepal', title: 'Непал' },
      { value: 'Netherlands', title: 'Нидерланды' },
      { value: 'Netherlands Antilles', title: 'Нидерландские Антильские острова' },
      { value: 'New Caledonia', title: 'Новая Каледония' },
      { value: 'New Zealand', title: 'Новая Зеландия' },
      { value: 'Nicaragua', title: 'Никарагуа' },
      { value: 'Niger', title: 'Нигер' },
      { value: 'Nigeria', title: 'Нигерия' },
      { value: 'Niue', title: 'Ниуэ' },
      { value: 'Norfolk Island', title: 'Норфолк' },
      { value: 'Northern Mariana Islands', title: 'Северные Марианские Острова' },
      { value: 'Norway', title: 'Норвегия' },
      { value: 'Oman', title: 'Оман' },
      { value: 'Pakistan', title: 'Пакистан' },
      { value: 'Palau', title: 'Палау' },
      { value: 'Palestinian Territory, Occupied', title: 'Палестина' },
      { value: 'Panama', title: 'Панама' },
      { value: 'Papua New Guinea', title: 'Папуа — Новая Гвинея' },
      { value: 'Paraguay', title: 'Парагвай' },
      { value: 'Peru', title: 'Перу' },
      { value: 'Philippines', title: 'Филипины' },
      { value: 'Pitcairn', title: 'Острова Питкэрн' },
      { value: 'Poland', title: 'Польша' },
      { value: 'Portugal', title: 'Португалия' },
      { value: 'Puerto Rico', title: 'Пуэрто-Рико' },
      { value: 'Qatar', title: 'Катар' },
      { value: 'Reunion', title: 'Реюньон' },
      { value: 'Romania', title: 'Румыния' },
      { value: 'Russia', title: 'Россия' },
      { value: 'RWANDA', title: 'Руанда' },
      { value: 'Samoa', title: 'Самоа' },
      { value: 'San Marino', title: 'Сан Марино' },
      { value: 'Saudi Arabia', title: 'Саудовская Аравия' },
      { value: 'Senegal', title: 'Сенегал' },
      { value: 'Seychelles', title: 'Сейшеллы' },
      { value: 'Sierra Leone', title: 'Сьерра-Леоне' },
      { value: 'Singapore', title: 'Сингапур' },
      { value: 'Slovakia', title: 'Словакия' },
      { value: 'Slovenia', title: 'Словения' },
      { value: 'Somalia', title: 'Сомали' },
      { value: 'South Africa', title: 'Южная Африка' },
      { value: 'Spain', title: 'Испания' },
      { value: 'Sri Lanka', title: 'Шри Ланка' },
      { value: 'Sudan', title: 'Судан' },
      { value: 'Suriname', title: 'Суринам' },
      { value: 'Sweden', title: 'Швеция' },
      { value: 'Switzerland', title: 'Швейцария' },
      { value: 'Syrian Arab Republic', title: 'Сирия' },
      { value: 'Taiwan, Province of China', title: 'Тайвань' },
      { value: 'Tajikistan', title: 'Таджикистан' },
      { value: 'Tanzania, United Republic of', title: 'Танзания' },
      { value: 'Thailand', title: 'Таиланд' },
      { value: 'Togo', title: 'Того' },
      { value: 'Tokelau', title: 'Токелау' },
      { value: 'Tonga', title: 'Тонга' },
      { value: 'Trinidad and Tobago', title: 'Тринидад и Тобаго' },
      { value: 'Tunisia', title: 'Тунис' },
      { value: 'Turkey', title: 'Турция' },
      { value: 'Turkmenistan', title: 'Туркменистан' },
      { value: 'Uganda', title: 'Уганда' },
      { value: 'Ukraine', title: 'Украина' },
      { value: 'United Arab Emirates', title: 'Объединённые Арабские Эмираты' },
      { value: 'United Kingdom', title: 'Великобритания' },
      { value: 'United States', title: 'США' },
      { value: 'Uruguay', title: 'Уругвай' },
      { value: 'Uzbekistan', title: 'Узбекистан' },
      { value: 'Venezuela', title: 'Венесуэла' },
      { value: 'Viet Nam', title: 'Вьетнам' },
      { value: 'Yemen', title: 'Йемен' },
      { value: 'Zambia', title: 'Замбия' },
      { value: 'Zimbabwe', title: 'Зимбабве' },
      { value: 'Unknown', title: 'Неизвестно' },
    ],
    statuses: [
      { title: 'Любой', value: '' },
      { title: 'Активны', value: 'Active' },
      { title: 'Распались', value: 'Split-up' },
      { title: 'В заморозке', value: 'On hold' },
      { title: 'Неизвестно', value: 'Unknown' },
      { title: 'Сменили название', value: 'Changed name' }
    ],
  }),
  actions: {
    // ---------------------------------------GET---------------------------------------

    // ---------------------------------------POST---------------------------------------

    // ---------------------------------------PATCH---------------------------------------
    axiosErrorHandler(error) {
      toast.error(`Текст ошибки:\n${error.response.data.error}`)
    },
  },
  getters: {
    sortedCountries() {
      return sortBy(this.countries, 'title')
    }
  }
})
